/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.etec.sgdga.tela;

import br.com.etec.sgdga.control.BasicCliente;
import br.com.etec.sgdga.control.BasicItemNota;
import br.com.etec.sgdga.control.BasicNota;
import br.com.etec.sgdga.control.BasicProduto;
import br.com.etec.sgdga.control.ControleCliente;
import br.com.etec.sgdga.control.ControleItemNota;
import br.com.etec.sgdga.control.ControleNota;
import br.com.etec.sgdga.control.ControleProduto;
import java.awt.HeadlessException;
import java.sql.Date;
import java.sql.Time;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Windows
 */
public class TelaNota extends javax.swing.JFrame {

    DefaultTableModel tmNotas = new DefaultTableModel(null, new String[]{"N°", "Produto", "Quantidade", "V. Unidade", "SubTotal"}) {
        @Override
        public boolean isCellEditable(int rowIndex, int mColIndex) {
            return false;
        }
    };

    List<BasicCliente> clientes;
    List<BasicProduto> produtos;
    List<BasicNota> nota = new ArrayList<>();
    List<BasicItemNota> item = new ArrayList<>();

    double valor = 0;

    int n = 0;
    int hh, mm, ss; //*  
    Calendar hora; //*Hora  
    DecimalFormat formato; //*  
    relVenda vd = null;

    public TelaNota() {
        initComponents();
        listarCliente();
        listarProduto();
        ControleNota idd = new ControleNota();
        txtID.setText(String.valueOf(idd.buscarIdUltimaVenda() + 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbProduto = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNota = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnFinalizar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtValor = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFinal = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Restrar Vendas");
        setMinimumSize(new java.awt.Dimension(447, 398));

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0, 5, 0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setText("ID da Nota");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel1, gridBagConstraints);

        txtID.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(txtID, gridBagConstraints);

        jLabel4.setText("Cliente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel4, gridBagConstraints);

        cbCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(cbCliente, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Registrar Vendas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel1.add(jLabel8, gridBagConstraints);

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Produto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(jLabel2, gridBagConstraints);

        cbProduto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(cbProduto, gridBagConstraints);

        jLabel3.setText("Quantidade:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(jLabel3, gridBagConstraints);

        txtQuantidade.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(txtQuantidade, gridBagConstraints);

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/etec/sgdga/res/img/32/cart_add.png"))); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(btnAdicionar, gridBagConstraints);

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/etec/sgdga/res/img/32/cart_delete.png"))); // NOI18N
        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(btnRemover, gridBagConstraints);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/etec/sgdga/res/img/32/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(btnCancelar, gridBagConstraints);

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        tbNota.setBorder(new javax.swing.border.MatteBorder(null));
        tbNota.setModel(tmNotas);
        jScrollPane1.setViewportView(tbNota);

        java.awt.GridBagLayout jPanel4Layout = new java.awt.GridBagLayout();
        jPanel4Layout.columnWidths = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel4Layout.rowHeights = new int[] {0};
        jPanel4.setLayout(jPanel4Layout);

        btnFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/etec/sgdga/res/img/32/cash_register.png"))); // NOI18N
        btnFinalizar.setText("Finalizar Venda");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = -8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel4.add(btnFinalizar, gridBagConstraints);

        jLabel6.setText("Valor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel4.add(jLabel6, gridBagConstraints);

        txtValor.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(txtValor, gridBagConstraints);

        jLabel7.setText("Desconto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel4.add(jLabel7, gridBagConstraints);

        txtDesconto.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 56;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(txtDesconto, gridBagConstraints);

        jLabel5.setText("Valor Total:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel4.add(jLabel5, gridBagConstraints);

        txtFinal.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(txtFinal, gridBagConstraints);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void listarCliente() {
        ControleCliente cli = new ControleCliente();
        clientes = cli.listarClientes("%%");
        cbCliente.removeAllItems();
        for (int i = 0; i < clientes.size(); i++) {
            cbCliente.addItem(clientes.get(i).getNome());
        }
    }

    private void listarProduto() {
        ControleProduto prod = new ControleProduto();
        produtos = prod.listarProdutos("%%");
        cbProduto.removeAllItems();
        for (int i = 0; i < produtos.size(); i++) {
            cbProduto.addItem(produtos.get(i).getNome());
        }
    }

    public void removerItem(int linha) {
        try {

            if (tbNota.getSelectedRow() != -1) {

                double valorRemovido;
                double valorTotal;
                valorRemovido = Double.valueOf(tmNotas.getValueAt(linha, 3).toString());
                valorTotal = Double.valueOf(txtValor.getValue().toString());

                txtValor.setValue(valorTotal - valorRemovido);
                txtFinal.setValue(valorTotal - valorRemovido - Double.parseDouble(txtDesconto.getText()));
                tmNotas.removeRow(linha);
                item.remove(linha);
                valor = valorTotal - valorRemovido;

            } else {
                JOptionPane.showMessageDialog(this, "Selecionar o item a  ser removido");
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void cancelarVenda() {
        while (tmNotas.getRowCount() > 0) {
            tmNotas.removeRow(0);
        }
        valor = 0;
        nota.clear();
        this.dispose();
        txtValor.setValue(0);
        txtDesconto.setValue(0);
        txtFinal.setValue(0);
    }

    private boolean verificarQuantidade() {

        try {
            if (Integer.parseInt(txtQuantidade.getText()) > 0) {
                return true;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, ex, "Erro", 0);

        }

        return false;
    }

    private void incluirProduto() {
        if (verificarQuantidade()) {

            BasicItemNota vb = new BasicItemNota();

            if (produtos.get(cbProduto.getSelectedIndex()).getEstoque() > Integer.parseInt(txtQuantidade.getText())) {
                vb.setNota(Integer.parseInt(txtID.getText()));
                vb.setProduto(produtos.get(cbProduto.getSelectedIndex()).getId());
                vb.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
                vb.setValorUni(produtos.get(cbProduto.getSelectedIndex()).getValor_final());
                vb.setSubTotal(produtos.get(cbProduto.getSelectedIndex()).getValor_final() * Integer.valueOf(txtQuantidade.getText()));

                item.add(vb);
                n = n + 1;
                String id = String.valueOf(n);
                String produto = produtos.get(cbProduto.getSelectedIndex()).getNome();
                String quantidade = txtQuantidade.getText();
                String tot = String.valueOf(produtos.get(cbProduto.getSelectedIndex()).getValor_final());
                String sub = String.valueOf(produtos.get(cbProduto.getSelectedIndex()).getValor_final() * Integer.parseInt(txtQuantidade.getText()));

                // String total;
                //    total = String.valueOf(produtos.get(cbProduto.getSelectedIndex()).getValor_final() * Integer.parseInt(quantidade));
                String[] campos = new String[]{id, produto, quantidade, tot, sub};
                tmNotas.addRow(campos);
                valor += produtos.get(cbProduto.getSelectedIndex()).getValor_final() * Integer.parseInt(quantidade);
                txtValor.setValue(valor);

                if (txtDesconto.getText().trim().length() > 0) {
                    txtFinal.setValue(valor - Integer.parseInt(txtDesconto.getText()));
                } else {
                    txtFinal.setValue(valor);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Desculpe, não temos esta quantidade no estoque\n" + produtos.get(cbProduto.getSelectedIndex()).getNome() + "  " + produtos.get(cbProduto.getSelectedIndex()).getEstoque(), "Erro", 0);
                txtQuantidade.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Quantidade Invalida\nInserir outro valor", "Erro", 0);
            txtQuantidade.requestFocus();
        }

    }

    private void cadastrarVenda() {
        if (!nota.isEmpty()) {/////////////////////////////////////////////
            JOptionPane.showMessageDialog(this, "Incluir pelo menos um produto!!", "Erro", 0);
        } else {
            try {

                BasicNota no = new BasicNota();
                java.util.Date d = new java.util.Date();

                SimpleDateFormat formatod = new SimpleDateFormat("yyyy-MM-dd");
                Date data = Date.valueOf(formatod.format(d));

                hora = Calendar.getInstance();
                hh = hora.get(Calendar.HOUR_OF_DAY);
                mm = hora.get(Calendar.MINUTE);
                ss = hora.get(Calendar.SECOND);

                hora = Calendar.getInstance();
                hh = hora.get(Calendar.HOUR_OF_DAY);
                mm = hora.get(Calendar.MINUTE);
                no.setCliente(clientes.get(cbCliente.getSelectedIndex()).getId());
                no.setData(data);
                no.setHora(Time.valueOf(formatar(hh) + ":" + formatar(mm) + ":" + formatar(ss)));
                no.setPagamento(1);
                try {
                    no.setValor(Double.valueOf(txtValor.getText().trim()));
                    no.setDesconto(Double.valueOf(txtDesconto.getText().trim()));
                    no.setValorFinal(Double.valueOf(txtFinal.getText().trim()));
                } catch (NumberFormatException e) {
                    no.setValor(Float.valueOf(txtValor.getText().trim().replaceAll(",", ".")));
                    no.setDesconto(Float.valueOf(txtDesconto.getText().trim().replaceAll(",", ".")));
                    no.setValorFinal(Float.valueOf(txtFinal.getText().trim().replaceAll(",", ".")));
                }
                ControleNota c = new ControleNota();
                c.cadastrarNotas(no);

                ControleItemNota ven = new ControleItemNota();
                for (int i = 0; i < item.size(); i++) {

                    ven.cadastrarItemNotas(item.get(i));

                }

                JOptionPane.showMessageDialog(this, "Venda Cadastrada com sucesso", "Certo", 1);
                int res = JOptionPane.showConfirmDialog(this, "Deseja Imprimir a nota", "Confirmação", JOptionPane.YES_NO_OPTION, 2);
                if (res == JOptionPane.YES_OPTION) {
                    if (vd == null) {
                        vd = new relVenda();
                        vd.setVisible(true);
                        vd.Iniciar(Integer.parseInt(txtID.getText()));
                    } else {
                        vd.setVisible(true);
                        vd.setState(JFrame.NORMAL);
                        vd.Iniciar(Integer.parseInt(txtID.getText()));
                    }
                }
                cancelarVenda();
            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(this, "Erro ao Cadastrar venda", "Erro", 0);

            }
        }
    }

    private String formatar(int num) {
        formato = new DecimalFormat("00");
        return formato.format(num);
    }

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        incluirProduto();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        cadastrarVenda();
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        removerItem(tbNota.getSelectedRow());
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelarVenda();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaNota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JComboBox cbCliente;
    private javax.swing.JComboBox cbProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbNota;
    private javax.swing.JFormattedTextField txtDesconto;
    private javax.swing.JFormattedTextField txtFinal;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JFormattedTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
