/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.etec.sgdga.tela;

import br.com.etec.sgdga.control.BasicCheque;
import br.com.etec.sgdga.control.CnpjValido;
import br.com.etec.sgdga.control.ControleCheque;
import br.com.etec.sgdga.control.CpfValido;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Windows
 */
public class TelaCheque extends javax.swing.JFrame {

    DefaultTableModel tmCheques = new DefaultTableModel(null, new String[]{"Banco", "Agencia", "Conta", "Valor", "Cpf/Cnpj"}) {
        @Override
        public boolean isCellEditable(int rowIndex, int mColIndex) {
            return false;
        }
    };
    ListSelectionModel lsmCheque;
    List<BasicCheque> cheques;
    String tipoCadastro;

    public TelaCheque() {
        initComponents();
        atualizarCheque();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBanco = new javax.swing.JTextField();
        txtAgencia = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtPrazo = new javax.swing.JTextField();
        txtVencimento = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter celular= new javax.swing.text.MaskFormatter("####-##-##");
            txtVencimento = new javax.swing.JFormattedTextField(celular);
        }
        catch (Exception e){
        }
        txtCnpj = new javax.swing.JTextField();
        txtConta = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btNovo = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btDeletar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCheque = new javax.swing.JTable();
        txtProcurar = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cheque");
        setMaximumSize(new java.awt.Dimension(500, 2147483647));
        setMinimumSize(new java.awt.Dimension(450, 450));
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setText("Banco:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Agência:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Conta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("N° Cheque:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Valor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Prazo em Dia:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Vencimento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(jLabel7, gridBagConstraints);

        jLabel8.setText("CPF/CNPJ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(jLabel8, gridBagConstraints);

        txtBanco.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(txtBanco, gridBagConstraints);

        txtAgencia.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(txtAgencia, gridBagConstraints);

        txtNumero.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(txtNumero, gridBagConstraints);

        txtPrazo.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(txtPrazo, gridBagConstraints);

        txtVencimento.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(txtVencimento, gridBagConstraints);

        txtCnpj.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(txtCnpj, gridBagConstraints);

        txtConta.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(txtConta, gridBagConstraints);

        txtValor.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(txtValor, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("Cadastrar Cheque");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(jLabel9, gridBagConstraints);

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/etec/sgdga/res/img/32/page_add.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel2.add(btNovo, gridBagConstraints);

        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/etec/sgdga/res/img/32/page_edit.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel2.add(btAlterar, gridBagConstraints);

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/etec/sgdga/res/img/32/page_save.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setEnabled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel2.add(btSalvar, gridBagConstraints);

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/etec/sgdga/res/img/32/cancel.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.setEnabled(false);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel2.add(btCancelar, gridBagConstraints);

        btDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/etec/sgdga/res/img/32/page_delete.png"))); // NOI18N
        btDeletar.setText("Apagar");
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel2.add(btDeletar, gridBagConstraints);

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        tbCheque.setModel(tmCheques);
        tbCheque.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmCheque = tbCheque.getSelectionModel();
        lsmCheque.addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent e){
                tbChequeLinhaSelecionada(tbCheque);
            }
        });
        jScrollPane1.setViewportView(tbCheque);

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/etec/sgdga/res/img/32/magnifier.png"))); // NOI18N
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        jLabel10.setText("Pesquisar Cheque por numero");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProcurar)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btPesquisar)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    protected void tbChequeLinhaSelecionada(JTable tb) {
        if (tb.getSelectedRow() != -1) {
            txtBanco.setText(cheques.get(tb.getSelectedRow()).getBanco());
            txtAgencia.setText(cheques.get(tb.getSelectedRow()).getAgencia());
            txtNumero.setText(cheques.get(tb.getSelectedRow()).getNumeroCheque());
            txtPrazo.setText(cheques.get(tb.getSelectedRow()).getPrazo());
            txtVencimento.setText(String.valueOf(cheques.get(tb.getSelectedRow()).getVencimento()));
            txtCnpj.setText(cheques.get(tb.getSelectedRow()).getCnpj());
            txtConta.setText(cheques.get(tb.getSelectedRow()).getConta());
            txtValor.setText(String.valueOf(cheques.get(tb.getSelectedRow()).getValor()));

        } else {
            limpaCampos();
        }
    }

    protected void listarCheque() {
        ControleCheque che = new ControleCheque();
        cheques = che.listarCheques("%" + txtProcurar.getText().trim() + "%");
        mostrarCheque(cheques);
    }

    protected void mostrarCheque(List<BasicCheque> cheques) {

        while (tmCheques.getRowCount() > 0) {
            tmCheques.removeRow(0);
        }

        if (cheques.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum Registro Encontrado", "Erro", 0);
        } else {

            String[] campos = new String[]{null, null, null, null, null};
            for (int i = 0; i < cheques.size(); i++) {
                tmCheques.addRow(campos);

                tmCheques.setValueAt(cheques.get(i).getBanco(), i, 0);
                tmCheques.setValueAt(cheques.get(i).getAgencia(), i, 1);
                tmCheques.setValueAt(cheques.get(i).getConta(), i, 2);
                tmCheques.setValueAt(cheques.get(i).getValor(), i, 3);
                tmCheques.setValueAt(cheques.get(i).getCnpj(), i, 4);

            }
        }

    }

    protected boolean verificarCampos() {
        int a = txtBanco.getText().length();
        int b = txtAgencia.getText().length();
        int c = txtNumero.getText().length();
        int d = txtPrazo.getText().length();
        int e = txtVencimento.getText().length();
        int f = txtCnpj.getText().length();
        int g = txtConta.getText().length();
        int h = txtValor.getText().length();

        CnpjValido cnpj = new CnpjValido();
        CpfValido cpf = new CpfValido();

        if (a > 0 && a < 7) {
            if (b > 0 && b < 4) {
                if (c > 0 && c < 7) {
                    if (d > 0 && d < 4) {
                        if (e > 0 && e < 11) {
                            if (f > 13 && f < 19) {
                                if (cnpj.CNPJ(txtCnpj.getText().trim()) || cpf.CPF(txtCnpj.getText().trim())) {
                                    if (g > 0 && g < 6) {
                                        if (h > 0 && h < 10) {
                                            return true;
                                        } else {
                                            JOptionPane.showMessageDialog(rootPane, "Preencher o valor", "Aviso", 0);
                                            txtValor.requestFocus();
                                            return false;
                                        }
                                    } else {
                                        JOptionPane.showMessageDialog(rootPane, "Preencher  a conta", "Aviso", 0);
                                        txtConta.requestFocus();
                                        return false;
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(rootPane, "Preencher um cnpj ou cpf Valido", "Aviso", 0);
                                    txtCnpj.requestFocus();
                                    return false;
                                }
                            } else {
                                JOptionPane.showMessageDialog(rootPane, "Preencher um cnpj ou cpf", "Aviso", 0);
                                txtCnpj.requestFocus();
                                return false;
                            }
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Preencher a data do vencimento", "Aviso", 0);
                            txtVencimento.requestFocus();
                            return false;
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Preencher um prazo", "Aviso", 0);
                        txtPrazo.requestFocus();
                        return false;
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Preencher o numero do cheque", "Aviso", 0);
                    txtNumero.requestFocus();
                    return false;
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Preencher a agencia", "Aviso", 0);
                txtAgencia.requestFocus();
                return false;
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Preencher o numero do banco", "Aviso", 0);
            txtBanco.requestFocus();
            return false;
        }

    }

    protected void cadastraCheque() {

        if (verificarCampos()) {
            BasicCheque cheque = new BasicCheque();
            cheque.setBanco(txtBanco.getText().trim());
            cheque.setAgencia(txtAgencia.getText().trim());
            cheque.setNumeroCheque(txtNumero.getText().trim());
            cheque.setPrazo(txtPrazo.getText().trim());
            cheque.setVencimento(Date.valueOf(txtVencimento.getText().trim()));
            cheque.setCnpj(txtCnpj.getText().trim());
            cheque.setConta(txtConta.getText().trim());
            cheque.setValor(Double.parseDouble(txtValor.getText().trim()));

            ControleCheque c = new ControleCheque();
            c.cadastrarCheques(cheque);
            JOptionPane.showMessageDialog(this, "Registro feito com sucesso\n" + cheque.getNumeroCheque(), "Registro", 1);
            desabilitarCampos();
        }

    }

    protected void habilitarCampos() {
        txtBanco.setEditable(true);
        txtAgencia.setEditable(true);
        txtNumero.setEditable(true);
        txtPrazo.setEditable(true);
        txtVencimento.setEditable(true);
        txtCnpj.setEditable(true);
        txtConta.setEditable(true);
        txtValor.setEditable(true);
        btSalvar.setEnabled(true);
        btAlterar.setEnabled(false);
        btNovo.setEnabled(false);
        btDeletar.setEnabled(false);
        tbCheque.setEnabled(false);
        btPesquisar.setEnabled(false);
        txtProcurar.setEnabled(false);
        btCancelar.setEnabled(true);
    }

    protected void desabilitarCampos() {
        txtBanco.setEditable(false);
        txtAgencia.setEditable(false);
        txtNumero.setEditable(false);
        txtPrazo.setEditable(false);
        txtVencimento.setEditable(false);
        txtCnpj.setEditable(false);
        txtConta.setEditable(false);
        txtValor.setEditable(false);
        btSalvar.setEnabled(false);
        btAlterar.setEnabled(true);
        btNovo.setEnabled(true);
        btDeletar.setEnabled(true);
        tbCheque.setEnabled(true);
        btPesquisar.setEnabled(true);
        txtProcurar.setEnabled(true);
        btCancelar.setEnabled(false);
    }

    private void limpaCampos() {
        txtBanco.setText("");
        txtAgencia.setText("");
        txtNumero.setText("");
        txtPrazo.setText("");
        txtVencimento.setText("");
        txtCnpj.setText("");
        txtConta.setText("");
        txtValor.setText("");
    }

    protected void alteraCheque() {
        if (tbCheque.getSelectedRow() != -1) {
            habilitarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum Registro Selecionado na Tabela", "Erro", 0);
        }
    }

    protected void alterarCheque() {
        if (verificarCampos()) {
            BasicCheque cheque = new BasicCheque();
            cheque.setId(cheques.get(tbCheque.getSelectedRow()).getId());

            cheque.setBanco(txtBanco.getText().trim());
            cheque.setAgencia(txtAgencia.getText().trim());
            cheque.setNumeroCheque(txtNumero.getText().trim());
            cheque.setPrazo(txtPrazo.getText().trim());
            cheque.setVencimento(Date.valueOf(txtVencimento.getText().trim()));
            cheque.setCnpj(txtCnpj.getText().trim());
            cheque.setConta(txtConta.getText().trim());
            cheque.setValor(Double.parseDouble(txtValor.getText().trim()));

            ControleCheque c = new ControleCheque();
            c.alterarCheques(cheque);
            JOptionPane.showMessageDialog(this, "Registro alterado com sucesso\n" + cheque.getNumeroCheque(), "Registro", 1);
            desabilitarCampos();
        }
    }

    private void novoCliente() {
        habilitarCampos();
        limpaCampos();
    }

    protected void excluirCheque() {
        if (tbCheque.getSelectedRow() != -1) {
            int res = JOptionPane.showConfirmDialog(this, "Deseja apagar este registro?", "Confirmação", JOptionPane.YES_NO_OPTION, 2);
            if (res == JOptionPane.YES_OPTION) {
                ControleCheque pc = new ControleCheque();
                pc.excluirCheques(cheques.get(tbCheque.getSelectedRow()).getId());
                JOptionPane.showMessageDialog(this, "Registro apagado com sucesso", "Registro", 0);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum Registro Selecionado na Tabela", "Erro", 0);
        }
    }

    //
    protected void atualizarCheque() {
        ControleCheque che = new ControleCheque();
        cheques = che.listarCheques("%%");
        ExibeCheque(cheques);
    }

    protected void ExibeCheque(List<BasicCheque> grup) {

        while (tmCheques.getRowCount() > 0) {
            tmCheques.removeRow(0);
        }

        if (!grup.isEmpty()) {

            String[] campos = new String[]{null, null};
            for (int i = 0; i < grup.size(); i++) {
                tmCheques.addRow(campos);

                tmCheques.setValueAt(cheques.get(i).getBanco(), i, 0);
                tmCheques.setValueAt(cheques.get(i).getAgencia(), i, 1);
                tmCheques.setValueAt(cheques.get(i).getConta(), i, 2);
                tmCheques.setValueAt(cheques.get(i).getValor(), i, 3);
                tmCheques.setValueAt(cheques.get(i).getCnpj(), i, 4);

            }
        }

    }

    //
    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        novoCliente();
        tipoCadastro = "novo";

    }//GEN-LAST:event_btNovoActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        tipoCadastro = "alteracao";

        alteraCheque();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        switch (tipoCadastro) {
            case "novo":
                cadastraCheque();
                break;
            case "alteracao":
                alterarCheque();
                break;
        }
        atualizarCheque();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        limpaCampos();
        desabilitarCampos();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        listarCheque();
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed
        excluirCheque();
        atualizarCheque();
    }//GEN-LAST:event_btDeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaCheque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btDeletar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCheque;
    private javax.swing.JTextField txtAgencia;
    private javax.swing.JTextField txtBanco;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtConta;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPrazo;
    private javax.swing.JTextField txtProcurar;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtVencimento;
    // End of variables declaration//GEN-END:variables
}
